/**
 * Pinned built-in Marinara macro names from official docs at
 * Pasta-Devs/Marinara-Engine b7545a63e7e264a1cd9eeea1a5490d50c08ddb29
 * prompts/macros.md. Static floor only; live /macros may add more.
 */
export const MARINARA_ENGINE_COMMIT =
  "b7545a63e7e264a1cd9eeea1a5490d50c08ddb29";

/** Canonical names without braces; aliases listed separately where needed. */
export const MARINARA_BUILTIN_MACROS: readonly string[] = [
  "user",
  "userName",
  "userNamePhonetic",
  "char",
  "charName",
  "charNamePhonetic",
  "characters",
  "group",
  "persona",
  "personaDescription",
  "personaPersonality",
  "personaBackstory",
  "personaAppearance",
  "personaScenario",
  "description",
  "personality",
  "backstory",
  "appearance",
  "scenario",
  "example",
  "charSysInfo",
  "charPostHistory",
  "convo_display",
  "char_about",
  "persona_about",
  "convo_behavior",
  "context",
  "status",
  "commands",
  "commandList",
  "reactRules",
  "emojiReact",
  "replyRules",
  "memories",
  "memoryRecall",
  "lorebook",
  "lore",
  "input",
  "model",
  "chatId",
  "lastGenerationType",
  "idle_duration",
  "gameStoryboardKeyframeCount",
  "date",
  "time",
  "datetime",
  "isotime",
  "weekday",
  "timezone",
  "random",
  "newline",
  "trim",
  "trimStart",
  "trimEnd",
  "noop",
] as const;

/** Substrings that must appear in catalog or prompts docs for argument-bearing forms. */
export const MARINARA_MACRO_FORMS: readonly string[] = [
  "agent::TYPE",
  "random:X:Y",
  "random::",
  "roll:XdY",
  "setvar::name::value",
  "getvar::name",
  "addvar::name::value",
  "incvar::name",
  "decvar::name",
  "{{uppercase}}",
  "{{lowercase}}",
  "{{// comment}}",
  "banned",
  "{{\\n}}",
] as const;

export const MARINARA_CONDITIONAL_OPERATORS: readonly string[] = [
  "==",
  "=",
  "is",
  "!=",
  "is not",
  ">",
  "<",
  ">=",
  "<=",
  "contains",
  "includes",
  "not contains",
  "not includes",
  "&&",
  "||",
] as const;
