/**
 * Fully populated canonical fixtures used to prove every authored runtime branch parses.
 */
import { CANONICAL_SCHEMA_VERSION } from "../core/canonical";
import type { CanonicalCharacter } from "./character/schema";
import type { CanonicalLorebook } from "./lorebook/schema";
import type { CanonicalPack } from "./pack/schema";
import type { CanonicalPersona } from "./persona/schema";
import type { CanonicalPreset } from "./preset/schema";
import type { CanonicalRegexSet } from "./regex/schema";

export const fullCharacter: CanonicalCharacter = {
  schemaVersion: CANONICAL_SCHEMA_VERSION,
  kind: "character",
  id: "full-character",
  body: {
    identity: {
      name: "Mira",
      nickname: "Mi",
      tagline: "Keeper of the archive",
      description: "An exacting archivist.",
      characterVersion: "2",
      fullName: "Mira Sol",
      title: "Archivist",
      age: "31",
      pronouns: "she/her",
      culture: "Aetherian",
    },
    persona: {
      personality: "Methodical",
      scenario: "The archive is flooding.",
      appearance: "Ink-stained coat",
      voice: {
        provider: "local",
        voiceId: "mira",
        rate: 1.1,
        pitch: 0.9,
        disabled: false,
        extras: { stability: 0.7 },
      },
      imagePrompt: {
        prompt: "archivist",
        prefix: "portrait",
        suffix: "library",
        negative: "blur",
        template: "{{prompt}}",
        instructions: "Keep the coat.",
        emotionInstructions: "Use readable expressions.",
        rows: [{ label: "always", value: "solo" }],
      },
      structured: {
        kind: "attributes",
        attributes: { temperament: ["methodical"] },
      },
    },
    prompts: {
      systemPrompt: "Stay in character.",
      postHistoryInstructions: "Answer precisely.",
      depthInjections: [{
        text: "The archive matters.",
        depth: 2,
        role: "system",
        origin: "depth_prompt",
        enabled: true,
      }],
      prefill: "Mira:",
      additionalText: "Remember the index.",
    },
    greetings: {
      firstMessage: "Welcome.",
      alternateGreetings: [{ text: "You made it.", title: "Late arrival", id: "late" }],
      groupOnlyGreetings: [{ text: "Everyone is here.", title: "Group", id: "group" }],
    },
    examples: { exampleMessages: "<START>\nMira: Filed." },
    media: {
      portrait: {
        role: "portrait",
        name: "main",
        label: "neutral",
        primary: true,
        ref: "asset://portrait",
        mime: "image/png",
      },
      assets: [{
        role: "emotion",
        name: "smile",
        label: "happy",
        primary: false,
        ref: "asset://happy",
        mime: "image/webp",
      }],
      sprite: {
        parts: { hair: "bob", coat: "long" },
        gender: "woman",
        eyeColor: "green",
        bodyColor: "warm",
        hairColor: "black",
      },
      visualKind: "sprite",
      faceLabel: "happy",
    },
    attribution: {
      creator: "Chi",
      originalCreator: "Chi",
      source: ["hoplight"],
      sourceUrl: "https://example.test/mira",
      license: "CC-BY-4.0",
      creatorNotes: "Full fixture",
      creatorNotesMultilingual: { en: "Full fixture" },
      publicNote: "Built for tests.",
      createdAt: 1,
      updatedAt: 2,
    },
    discovery: {
      tags: ["archive"],
      genre: "fantasy",
      fandom: "original",
      rating: "all-ages",
      contentWarnings: ["flood"],
    },
    presentation: {
      signatureColor: "jade",
      gradientColors: ["jade", "gold"],
      palette: [{ label: "ink", name: "Archive ink", hex: "#112233" }],
      background: { ref: "asset://library", overlayOpacity: 0.5, videoPlaybackRate: 1 },
      fieldOrder: ["identity", "persona"],
      spoilers: { mode: "manual", order: ["history"], fields: { history: true } },
      mediaLinks: ["https://example.test/reference"],
    },
    settings: {
      talkativeness: 0.6,
      risu: {
        viewScreen: "emotion",
        largePortrait: true,
        inlayViewScreen: false,
        utilityBot: false,
        lorePlus: true,
      },
      responseSchema: { type: "object" },
    },
    bias: [{ phrase: "archive", weight: 0.4 }],
    worldName: "Aetheria",
    knowledgeRefs: ["aetheria"],
    behavior: {
      regexScripts: [{
        label: "Trim",
        find: "\\s+$",
        replace: "",
        phase: "editoutput",
        flags: "g",
        useFlags: true,
      }],
      triggerScripts: [{
        label: "Arrival",
        event: "start",
        conditions: [{ type: "always" }],
        effects: [{ type: "set", key: "arrived" }],
      }],
      virtualScript: "sealed text",
      backgroundHTML: "<div>sealed</div>",
      backgroundCSS: ".sealed {}",
      defaultVariables: "{\"arrived\":false}",
      prebuiltAsset: { command: "portrait", exclude: ["blur"], style: "ink" },
      moduleToggles: "archive=true",
      privileged: false,
    },
    behaviorRefs: ["cleanup"],
    variants: [{
      id: "field",
      label: "Field work",
      mirrorBase: true,
      overrides: {
        identity: { nickname: "Scout" },
        persona: { structured: { kind: "text" } },
        media: { faceLabel: "focused" },
      },
    }],
  },
  profiles: { risu: { worldName: "Aetheria-Risu" } },
  original: {
    risu: {
      raw: { source: "fixture" },
      unmapped: { future: { preserved: true } },
      sourceMedia: { b64: "AA==", mime: "image/png" },
    },
  },
};
export const fullLorebook: CanonicalLorebook = {
  schemaVersion: CANONICAL_SCHEMA_VERSION,
  kind: "lorebook",
  id: "full-lorebook",
  body: {
    name: "Aetheria",
    description: "World reference",
    lorebookType: "world",
    genre: "fantasy",
    fandom: "original",
    tags: ["world"],
    enabled: true,
    globalCaseSensitive: false,
    globalMatchWholeWords: true,
    globalScanDepth: 8,
    globalRecursion: true,
    tokenBudget: 2048,
    budgetMode: "token",
    entryBudget: 20,
    entries: [{
      id: "archive",
      title: "Archive",
      content: "A flooded archive.",
      comment: "Core location",
      enabled: true,
      constant: false,
      triggerMode: "advanced",
      triggers: [{ keyword: "archive", isRegex: false, flags: "i", frequency: 1, probability: 90 }],
      secondaryTriggers: [{ keyword: "flood", isRegex: false, flags: "i", frequency: 2, probability: 80 }],
      selectiveLogic: "and_any",
      caseSensitive: false,
      matchWholeWords: true,
      scanDepth: 4,
      position: "depth",
      depth: 2,
      role: "system",
      sortOrder: 10,
      priority: 100,
      sticky: 1,
      cooldown: 2,
      delay: 0,
      groupName: "places",
      categoryId: "places",
      groupWeight: 100,
      probability: 95,
      useMemo: true,
      excludeRecursion: false,
      preventRecursion: false,
      delayUntilRecursion: 0,
      characterFilter: { names: ["Mira"], tags: ["archive"], isExclude: false },
      scanCharacterDescription: true,
      scanCharacterPersonality: true,
      scanUserPersona: true,
      scanScenario: true,
      scanCharacterDepthPrompt: true,
      scanCreatorNotes: true,
      ignoreBudget: false,
      vectorized: true,
      groupOverride: false,
      useGroupScoring: true,
      automationId: "open-archive",
      keyRelative: true,
      nonStoryActivatable: false,
      contextConfig: {
        prefix: "[",
        suffix: "]",
        tokenBudget: 256,
        reservedTokens: 32,
        trimDirection: "trimBottom",
        insertionType: "newline",
        maximumTrimType: "sentence",
        insertionPosition: 1,
      },
      loreBiasGroups: [{
        enabled: true,
        bias: 0.5,
        phrases: [{ sequence: "archive", sequences: ["old archive"], type: 1 }],
        whenInactive: false,
        generateOnce: true,
        ensureSequenceFinish: true,
      }],
      displayIndex: 1,
      sideEffects: {
        effects: [{ type: "setvar", variable: "visited", value: "yes", amount: 1, scope: "local" }],
        onlyOnFirstTrigger: true,
        clearOnDeactivate: false,
      },
      metadata: { platformDial: { enabled: true } },
    }],
    categories: [{ id: "places", name: "Places", sortOrder: 1, enabled: true }],
  },
};
export const fullPersona: CanonicalPersona = {
  schemaVersion: CANONICAL_SCHEMA_VERSION,
  kind: "persona",
  id: "full-persona",
  body: {
    name: "Chi",
    brief: "An engineer",
    content: "Curious and exacting.",
    sections: {
      appearance: "Glasses",
      body: "Tall",
      personality: "Curious",
      quirks: "Indexes everything",
      history: "Built Hoplight",
    },
    sectionOrder: ["history", "personality"],
    traits: ["curious"],
    identity: {
      tagline: "Builder",
      age: "adult",
      height: "tall",
      pronouns: "she/her",
      pronounSet: { subjective: "she", objective: "her", possessive: "hers" },
    },
    presentation: {
      signatureColor: "teal",
      colors: [{ label: "accent", name: "Teal", hex: "#008080" }],
      imageUrl: "asset://chi",
    },
    knowledgeRefs: ["aetheria"],
    rating: "all-ages",
    chatInjection: { position: "character", depth: 1, role: "user", wrapper: "The user is:" },
    attribution: { creator: "Chi", version: "1", createdAt: "2026-07-26", source: "hoplight" },
    media: {
      portrait: {
        role: "portrait",
        name: "main",
        label: "neutral",
        primary: true,
        ref: "asset://chi",
        mime: "image/png",
      },
    },
  },
};
export const fullPreset: CanonicalPreset = {
  schemaVersion: CANONICAL_SCHEMA_VERSION,
  kind: "preset",
  id: "full-preset",
  body: {
    name: "Writer",
    description: "Complete preset",
    enabled: true,
    prompts: [{
      id: "main",
      name: "Main",
      content: "Write clearly.",
      role: "system",
      enabled: true,
      systemPrompt: true,
      marker: false,
      markerSlot: "main",
      placement: "relative",
      injectionDepth: 0,
      injectionOrder: 100,
      forbidOverrides: false,
      injectionTrigger: ["normal"],
      isDefault: false,
      groupId: "core",
      wrapInXml: true,
      xmlTagName: "instruction",
      extras: { source: "fixture" },
    }],
    groups: [{
      id: "core",
      name: "Core",
      content: "Core prompts",
      parentGroupId: "root",
      order: 1,
      enabled: true,
      extras: { color: "teal" },
    }],
    samplers: {
      temperature: 0.7,
      topP: 0.9,
      topK: 40,
      topA: 0.1,
      minP: 0.05,
      frequencyPenalty: 0.2,
      presencePenalty: 0.1,
      repetitionPenalty: 1.05,
      maxContext: 8192,
      maxTokens: 512,
      promptPostProcessing: "merge",
      contextMode: "messages",
      maxMessages: 30,
    },
    systemPrompts: {
      impersonation: "Impersonate.",
      newChat: "New chat.",
      newGroupChat: "New group.",
      newExampleChat: "Example.",
      continueNudge: "Continue.",
      groupNudge: "Group.",
      assistantPrefill: "Assistant:",
      assistantImpersonation: "As assistant.",
    },
    templates: {
      worldInfoFormat: "{{world}}",
      scenarioFormat: "{{scenario}}",
      personalityFormat: "{{personality}}",
    },
    behavior: {
      wrapInQuotes: false,
      namesBehavior: 1,
      sendIfEmpty: "...",
      continuePrefill: true,
      continuePostfix: "\n",
    },
    apiOptions: {
      streamResponses: true,
      claudeUseSystemPrompt: true,
      useMakerSuiteSystemPrompt: false,
      squashSystemMessages: true,
      functionCalling: true,
      showThoughts: false,
      reasoningEffort: "medium",
      enableWebSearch: false,
      requestImages: false,
    },
    media: { imageInlining: true, inlineImageQuality: "high", videoInlining: false },
    generation: { seed: 42, completions: 1, maxContextUnlocked: false, biasPreset: "balanced" },
    choices: [{
      id: "tone",
      key: "tone",
      label: "Tone",
      readme: "Choose a tone.",
      type: "many",
      options: [{
        id: "warm",
        label: "Warm",
        description: "Friendly",
        value: "warm",
        enablesPrompts: ["main"],
        set: { "local:tone": "warm" },
      }],
      default: ["warm"],
      min: 1,
      placeholder: "Choose",
      suggestions: ["warm"],
      separator: ", ",
      randomPick: false,
      sortOrder: 1,
      extras: { source: "fixture" },
    }],
  },
};
export const fullRegex: CanonicalRegexSet = {
  schemaVersion: CANONICAL_SCHEMA_VERSION,
  kind: "regex",
  id: "full-regex",
  body: {
    name: "Cleanup",
    description: "Complete regex set",
    enabled: true,
    rules: [{
      id: "trim",
      label: "Trim",
      note: "Remove trailing space",
      find: "\\s+$",
      flags: "g",
      useFlags: true,
      replace: "",
      trimStrings: ["ignore"],
      phases: ["output", "future-phase"],
      targets: ["response"],
      substituteFind: "raw",
      minDepth: 0,
      maxDepth: 4,
      runOnEdit: true,
      characterIds: ["mira"],
      firstMatchOnly: false,
      condition: { ruleId: "prior", matched: true },
      overlay: false,
      enabled: true,
      sortOrder: 1,
      extras: { source: "fixture" },
    }],
  },
};
export const fullPack: CanonicalPack = {
  schemaVersion: CANONICAL_SCHEMA_VERSION,
  kind: "pack",
  id: "full-pack",
  body: {
    name: "Expressions",
    brief: "Complete pack",
    pack: {
      enabled: true,
      defaultLabel: "neutral",
      items: [{ id: "neutral", label: "neutral", ref: "asset://neutral", mime: "image/png" }],
    },
    groups: {
      mira: {
        enabled: false,
        defaultLabel: "happy",
        items: [{ id: "happy", label: "happy", ref: "asset://happy", mime: "image/webp" }],
      },
    },
  },
};

export const fullSurfaceEntities = [
  fullCharacter,
  fullLorebook,
  fullPersona,
  fullPreset,
  fullRegex,
  fullPack,
] as const;
