/**
 * Remote-access sidecar manager: the imperative shell that owns the Go sidecar process. It spawns the
 * binary, reads its control channel (line-delimited JSON on stdout) through the pure core
 * (sidecar-status.ts), tracks the current RemoteState, auto-opens the Tailscale sign-in page when the
 * node asks for it, and tears the process down. Side effects (spawn, browser-open) are injected so this
 * stays a thin edge over the tested pure core. One sidecar per manager; enable() is idempotent.
 */

import {
  OFF,
  parseDevicesLine,
  parseStatusLine,
  reduceRemoteState,
  unavailableState,
  type RemoteDevice,
  type RemoteState,
} from "./sidecar-status";

type Child = ReturnType<typeof Bun.spawn>;

/**
 * What a user is told when the mesh path cannot run here. Deliberately prose, with no path and no
 * spawn error: a field report arrived showing a raw `ENOENT ... uv_spawn 'C:\...\sidecar.exe'` in the
 * settings panel, which tells a user nothing they can act on and reads as a broken install. The
 * actionable half is that LAN mode is right below and needs no extra binary at all.
 */
export const NO_SIDECAR_DETAIL =
  "This copy of Hoplight was built without the Tailscale helper, so the private-mesh link cannot start. " +
  "LAN mode below works with no extra download.";

export interface SidecarManagerOptions {
  /**
   * Locate the sidecar binary, or return null when it is absent. A FUNCTION, not a path, because it is
   * re-run on every enable(): a developer who builds the sidecar while the studio is open then gets a
   * working button instead of a stale "unavailable" that only a restart clears.
   */
  resolveBin: () => string | null;
  /** the UNTRUSTED local address the sidecar reverse-proxies remote traffic into. */
  untrustedUpstream: string;
  /** CSPRNG secret the sidecar stamps and the trusted port refuses (C2). Generated by the caller. */
  sharedSecret: string;
  /** tsnet state dir; omit to use the sidecar default. */
  stateDir?: string;
  /** tailnet node name; keep it non-identifying. */
  hostname?: string;
  /** injected browser-open (server-security.openInBrowser); used to pop the sign-in page. */
  openUrl: (url: string) => void;
  /** notified on every state change (drives the /api/remote/status poll + any push). */
  onState?: (state: RemoteState) => void;
  /** auto-open the sign-in page the first time it is offered (default true). */
  autoOpenSignIn?: boolean;
}

export interface SidecarManager {
  /** Start the sidecar if not already running. Idempotent. */
  enable(): void;
  /** Stop the sidecar and return to the off state. */
  disable(): Promise<void>;
  /** The current remote-access state. */
  getState(): RemoteState;
  /** The devices currently connected (host-only view). */
  getDevices(): RemoteDevice[];
  /** Kick a connected device by its node id (host-only; instructs the sidecar to deny it). */
  kick(nodeId: string): void;
  /** Open the sign-in page on demand (when the user clicks, if auto-open was dismissed). */
  openSignIn(): void;
}

/** Consume a byte stream, hand each complete line to onLine. Flushes a trailing partial on close. */
async function pumpLines(
  stream: ReadableStream<Uint8Array>,
  onLine: (line: string) => void,
): Promise<void> {
  const reader = stream.getReader();
  const decoder = new TextDecoder();
  let buf = "";
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buf += decoder.decode(value, { stream: true });
    for (let nl = buf.indexOf("\n"); nl >= 0; nl = buf.indexOf("\n")) {
      onLine(buf.slice(0, nl));
      buf = buf.slice(nl + 1);
    }
  }
  if (buf.trim()) onLine(buf);
}

export function createSidecarManager(opts: SidecarManagerOptions): SidecarManager {
  let proc: Child | null = null;
  // Resolved once up front so the panel shows the truth BEFORE anyone clicks. Offering "Enable remote
  // access" in a build that cannot honour it is the actual defect behind the field report; the error
  // message was only how it surfaced.
  let state: RemoteState = opts.resolveBin() ? OFF : unavailableState(NO_SIDECAR_DETAIL);
  let devices: RemoteDevice[] = [];
  let openedSignIn = false;

  const setState = (next: RemoteState): void => {
    state = next;
    opts.onState?.(next);
  };

  const enable = (): void => {
    if (proc) return; // already running; idempotent
    // Re-checked here, not trusted from construction: fail closed on a binary that is still absent
    // rather than spawning a path and translating the OS error after the fact.
    const bin = opts.resolveBin();
    if (!bin) {
      setState(unavailableState(NO_SIDECAR_DETAIL));
      return;
    }
    openedSignIn = false;
    setState({ phase: "starting" });
    void startFresh(bin);
  };

  // Clear any sidecar orphaned by a previous app run (e.g. a hard crash before the parent-watch could
  // fire) so a stale node carrying an old secret can never shadow the fresh one we are about to start.
  const killOrphans = async (): Promise<void> => {
    try {
      const argv =
        process.platform === "win32"
          ? ["taskkill", "/F", "/IM", "sidecar.exe"]
          : ["pkill", "-f", "hoplight/sidecar"];
      await Bun.spawn(argv, {
        stdout: "ignore",
        stderr: "ignore",
        stdin: "ignore",
        windowsHide: true, // taskkill is a console app too; do not flash a window when we sweep orphans
      }).exited;
    } catch {
      /* no orphan to clear, or the killer is unavailable; not fatal */
    }
  };

  const startFresh = async (binPath: string): Promise<void> => {
    await killOrphans();
    if (proc) return; // a concurrent enable already won the race

    const args = [binPath, "-upstream", opts.untrustedUpstream, "-watch-parent"];
    if (opts.stateDir) args.push("-state-dir", opts.stateDir);
    if (opts.hostname) args.push("-hostname", opts.hostname);

    let child: Child;
    try {
      // stdin is a live pipe so the sidecar can watch it: the OS closes it when this process ends, which
      // the sidecar treats as "parent died, exit". stdout is the control channel; stderr is noise. The
      // shared secret goes via ENV, never argv, argv is world-readable in the process table (ps,
      // /proc/<pid>/cmdline, Task Manager), which would leak the entire untrusted-listener auth.
      child = Bun.spawn(args, {
        stdout: "pipe",
        stderr: "ignore",
        stdin: "pipe",
        // windowsHide (CREATE_NO_WINDOW) stops the console-subsystem sidecar from popping a terminal
        // window when the window-less packaged app spawns it. Belt-and-suspenders with the sidecar's
        // own -H=windowsgui build.
        windowsHide: true,
        env: { ...process.env, HOPLIGHT_SIDECAR_SECRET: opts.sharedSecret },
      });
    } catch (err) {
      // The technical detail belongs in the HOST's console, not in a panel a remote device can read:
      // /api/remote/status serves this state, and a spawn error carries an absolute local path.
      console.warn("remote: sidecar failed to start:", err instanceof Error ? err.message : err);
      // ENOENT here means the binary went away between resolving it and spawning it (a mid-run rebuild,
      // or a cleaner). That is the unavailable case, not a failure the user should retry into.
      const missing = err instanceof Error && "code" in err && err.code === "ENOENT";
      setState(
        missing
          ? unavailableState(NO_SIDECAR_DETAIL)
          : { phase: "error", error: "The private-mesh link could not start. LAN mode below still works." },
      );
      return;
    }
    proc = child;

    void pumpLines(child.stdout as ReadableStream<Uint8Array>, (line) => {
      const devs = parseDevicesLine(line);
      if (devs) {
        devices = devs;
        return;
      }
      const event = parseStatusLine(line);
      if (!event) return;
      const next = reduceRemoteState(state, event);
      setState(next);
      if (
        next.phase === "needs-login" &&
        next.signInUrl &&
        !openedSignIn &&
        (opts.autoOpenSignIn ?? true)
      ) {
        openedSignIn = true;
        opts.openUrl(next.signInUrl);
      }
    });

    void child.exited.then(() => {
      if (proc !== child) return; // superseded by a newer process
      proc = null;
      devices = [];
      if (state.phase !== "error" && state.phase !== "unavailable") setState(OFF);
    });
  };

  const disable = async (): Promise<void> => {
    const child = proc;
    proc = null;
    devices = [];
    // "unavailable" survives a turn-off: it describes the BUILD, not a switch position, so collapsing it
    // to "off" would re-offer an Enable button that cannot work.
    if (state.phase === "unavailable") return;
    if (child) {
      child.kill();
      await child.exited.catch(() => {});
    }
    setState(OFF);
  };

  const kick = (nodeId: string): void => {
    const child = proc;
    if (!child || !nodeId) return;
    const stdin = child.stdin;
    if (!stdin || typeof stdin === "number") return; // not a writable pipe
    try {
      stdin.write(`${JSON.stringify({ cmd: "kick", nodeId })}\n`);
      stdin.flush();
    } catch {
      /* the sidecar may have died; the device list refreshes on the next report */
    }
  };

  return {
    enable,
    disable,
    getState: () => state,
    getDevices: () => devices,
    kick,
    openSignIn: () => {
      if (state.signInUrl) opts.openUrl(state.signInUrl);
    },
  };
}
