/**
 * Remote-access sidecar manager: the imperative shell that owns the Go sidecar process. It spawns the
 * binary, reads its control channel (line-delimited JSON on stdout) through the pure core
 * (sidecar-status.ts), tracks the current RemoteState, auto-opens the Tailscale sign-in page when the
 * node asks for it, and tears the process down. Side effects (spawn, browser-open) are injected so this
 * stays a thin edge over the tested pure core. One sidecar per manager; enable() is idempotent.
 */

import {
  OFF,
  parseDevicesLine,
  parseStatusLine,
  reduceRemoteState,
  type RemoteDevice,
  type RemoteState,
} from "./sidecar-status";

type Child = ReturnType<typeof Bun.spawn>;

export interface SidecarManagerOptions {
  /** absolute path to the sidecar binary (sidecar.exe on Windows). */
  binPath: string;
  /** the UNTRUSTED local address the sidecar reverse-proxies remote traffic into. */
  untrustedUpstream: string;
  /** CSPRNG secret the sidecar stamps and the trusted port refuses (C2). Generated by the caller. */
  sharedSecret: string;
  /** tsnet state dir; omit to use the sidecar default. */
  stateDir?: string;
  /** tailnet node name; keep it non-identifying. */
  hostname?: string;
  /** injected browser-open (server-security.openInBrowser); used to pop the sign-in page. */
  openUrl: (url: string) => void;
  /** notified on every state change (drives the /api/remote/status poll + any push). */
  onState?: (state: RemoteState) => void;
  /** auto-open the sign-in page the first time it is offered (default true). */
  autoOpenSignIn?: boolean;
}

export interface SidecarManager {
  /** Start the sidecar if not already running. Idempotent. */
  enable(): void;
  /** Stop the sidecar and return to the off state. */
  disable(): Promise<void>;
  /** The current remote-access state. */
  getState(): RemoteState;
  /** The devices currently connected (host-only view). */
  getDevices(): RemoteDevice[];
  /** Kick a connected device by its node id (host-only; instructs the sidecar to deny it). */
  kick(nodeId: string): void;
  /** Open the sign-in page on demand (when the user clicks, if auto-open was dismissed). */
  openSignIn(): void;
}

/** Consume a byte stream, hand each complete line to onLine. Flushes a trailing partial on close. */
async function pumpLines(
  stream: ReadableStream<Uint8Array>,
  onLine: (line: string) => void,
): Promise<void> {
  const reader = stream.getReader();
  const decoder = new TextDecoder();
  let buf = "";
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buf += decoder.decode(value, { stream: true });
    for (let nl = buf.indexOf("\n"); nl >= 0; nl = buf.indexOf("\n")) {
      onLine(buf.slice(0, nl));
      buf = buf.slice(nl + 1);
    }
  }
  if (buf.trim()) onLine(buf);
}

export function createSidecarManager(opts: SidecarManagerOptions): SidecarManager {
  let proc: Child | null = null;
  let state: RemoteState = OFF;
  let devices: RemoteDevice[] = [];
  let openedSignIn = false;

  const setState = (next: RemoteState): void => {
    state = next;
    opts.onState?.(next);
  };

  const enable = (): void => {
    if (proc) return; // already running; idempotent
    openedSignIn = false;
    setState({ phase: "starting" });
    void startFresh();
  };

  // Clear any sidecar orphaned by a previous app run (e.g. a hard crash before the parent-watch could
  // fire) so a stale node carrying an old secret can never shadow the fresh one we are about to start.
  const killOrphans = async (): Promise<void> => {
    try {
      const argv =
        process.platform === "win32"
          ? ["taskkill", "/F", "/IM", "sidecar.exe"]
          : ["pkill", "-f", "hoplight/sidecar"];
      await Bun.spawn(argv, {
        stdout: "ignore",
        stderr: "ignore",
        stdin: "ignore",
        windowsHide: true, // taskkill is a console app too; do not flash a window when we sweep orphans
      }).exited;
    } catch {
      /* no orphan to clear, or the killer is unavailable; not fatal */
    }
  };

  const startFresh = async (): Promise<void> => {
    await killOrphans();
    if (proc) return; // a concurrent enable already won the race

    const args = [opts.binPath, "-upstream", opts.untrustedUpstream, "-watch-parent"];
    if (opts.stateDir) args.push("-state-dir", opts.stateDir);
    if (opts.hostname) args.push("-hostname", opts.hostname);

    let child: Child;
    try {
      // stdin is a live pipe so the sidecar can watch it: the OS closes it when this process ends, which
      // the sidecar treats as "parent died, exit". stdout is the control channel; stderr is noise. The
      // shared secret goes via ENV, never argv, argv is world-readable in the process table (ps,
      // /proc/<pid>/cmdline, Task Manager), which would leak the entire untrusted-listener auth.
      child = Bun.spawn(args, {
        stdout: "pipe",
        stderr: "ignore",
        stdin: "pipe",
        // windowsHide (CREATE_NO_WINDOW) stops the console-subsystem sidecar from popping a terminal
        // window when the window-less packaged app spawns it. Belt-and-suspenders with the sidecar's
        // own -H=windowsgui build.
        windowsHide: true,
        env: { ...process.env, HOPLIGHT_SIDECAR_SECRET: opts.sharedSecret },
      });
    } catch (err) {
      setState({ phase: "error", error: `could not start remote access: ${String(err)}` });
      return;
    }
    proc = child;

    void pumpLines(child.stdout as ReadableStream<Uint8Array>, (line) => {
      const devs = parseDevicesLine(line);
      if (devs) {
        devices = devs;
        return;
      }
      const event = parseStatusLine(line);
      if (!event) return;
      const next = reduceRemoteState(state, event);
      setState(next);
      if (
        next.phase === "needs-login" &&
        next.signInUrl &&
        !openedSignIn &&
        (opts.autoOpenSignIn ?? true)
      ) {
        openedSignIn = true;
        opts.openUrl(next.signInUrl);
      }
    });

    void child.exited.then(() => {
      if (proc !== child) return; // superseded by a newer process
      proc = null;
      devices = [];
      if (state.phase !== "error") setState(OFF);
    });
  };

  const disable = async (): Promise<void> => {
    const child = proc;
    proc = null;
    devices = [];
    if (child) {
      child.kill();
      await child.exited.catch(() => {});
    }
    setState(OFF);
  };

  const kick = (nodeId: string): void => {
    const child = proc;
    if (!child || !nodeId) return;
    const stdin = child.stdin;
    if (!stdin || typeof stdin === "number") return; // not a writable pipe
    try {
      stdin.write(`${JSON.stringify({ cmd: "kick", nodeId })}\n`);
      stdin.flush();
    } catch {
      /* the sidecar may have died; the device list refreshes on the next report */
    }
  };

  return {
    enable,
    disable,
    getState: () => state,
    getDevices: () => devices,
    kick,
    openSignIn: () => {
      if (state.signInUrl) opts.openUrl(state.signInUrl);
    },
  };
}
