/**
 * The starter-recipe catalog (REGEX-JEWEL-PLAN.md R5, QOL 4) - pure DATA, no logic. Curated from
 * RoleCall's template catalog (apps/rc/src/lib/regex/templates.ts, Chi's own code) plus the two
 * house originals the locked gallery wire specs (remove-bracket-text, stop-speaking-for-me).
 * Descriptions rewritten to house voice; every before/after pair is ENGINE-COMPUTED by the
 * generator and re-verified by template-catalog.test.ts - the gallery never shows an example the
 * engine did not produce. Dropped from RC on purpose: placeholder word-lists posing as features
 * (censor/soften/anonymize), fragile heuristics (wrap-dialogue, add-action-asterisks, oxford-comma,
 * wrap-code-blocks, reduce-adverbs), naive person-swaps that break quoted speech (first-to-third,
 * my-to-their), the alice|bob seed list, and the half-true escape-html-entities.
 * Types + helpers live in ./templates.ts (one concept per file; this file is the shelf of data).
 */
import type { RegexTemplateEntry } from "./templates";

export const TEMPLATE_CATALOG: readonly RegexTemplateEntry[] = [
  {
    id: "remove-ooc",
    category: "cleanup",
    name: "Remove OOC notes",
    does: "drops (OOC: ...) and ((...)) asides from the reply",
    find: "\\(\\s*OOC[:\\s][^)]*\\)|\\[\\s*OOC[:\\s][^\\]]*\\]|\\(\\([^)]+\\)\\)",
    flags: "gi",
    replace: "",
    phases: ["output"],
    before: "She smiled warmly. (OOC: Should I continue?)\n*waves hello* ((author note: first meeting))",
    after: "She smiled warmly. \n*waves hello* ",
  },
  {
    id: "remove-asterisk-actions",
    category: "cleanup",
    name: "Remove asterisk actions",
    does: "drops *waves hello* style action lines, keeps the speech",
    find: "\\*[^*]+\\*",
    flags: "g",
    replace: "",
    phases: ["output"],
    before: "Hello there! *smiles warmly* How are you?",
    after: "Hello there!  How are you?",
  },
  {
    id: "remove-quotes-around-dialogue",
    category: "cleanup",
    name: "Unquote dialogue",
    does: "strips the quotation marks around speech, keeps the words",
    find: "\"([^\"]+)\"",
    flags: "g",
    replace: "$1",
    phases: ["output"],
    before: "\"Hello,\" she said. \"How are you?\"",
    after: "Hello, she said. How are you?",
  },
  {
    id: "collapse-multiple-newlines",
    category: "cleanup",
    name: "Collapse blank lines",
    does: "squeezes three or more blank lines down to one gap",
    find: "\\n{3,}",
    flags: "g",
    replace: "\n\n",
    phases: ["output"],
    before: "First paragraph.\n\n\n\n\nSecond paragraph.",
    after: "First paragraph.\n\nSecond paragraph.",
  },
  {
    id: "trim-trailing-whitespace",
    category: "cleanup",
    name: "Trim line ends",
    does: "removes stray spaces and tabs at the end of every line",
    find: "[ \\t]+$",
    flags: "gm",
    replace: "",
    phases: ["output"],
    before: "Hello world   \nGoodbye world\t\t",
    after: "Hello world   \nGoodbye world",
  },
  {
    id: "asterisk-to-italics",
    category: "formatting",
    name: "Asterisks to underscores",
    does: "rewrites *emphasis* as _emphasis_ for apps that only render underscores",
    find: "\\*([^*]+)\\*",
    flags: "g",
    replace: "_$1_",
    phases: ["output"],
    before: "She *walked* slowly toward the *door*.",
    after: "She _walked_ slowly toward the _door_.",
  },
  {
    id: "curly-to-straight-quotes",
    category: "formatting",
    name: "Straighten curly quotes",
    does: "turns typographic quotes into plain straight quotes",
    find: "[“”„‟″‶]",
    flags: "g",
    replace: "\"",
    phases: ["output"],
    before: "“Hello,” she said, “how are you?”",
    after: "\"Hello,\" she said, \"how are you?\"",
  },
  {
    id: "curly-to-straight-apostrophe",
    category: "formatting",
    name: "Straighten curly apostrophes",
    does: "turns typographic apostrophes into plain ones",
    find: "[‘’‚‛′‵]",
    flags: "g",
    replace: "'",
    phases: ["output"],
    before: "I’m going to Sarah’s house.",
    after: "I'm going to Sarah's house.",
  },
  {
    id: "em-dash-to-double-hyphen",
    category: "formatting",
    name: "Em dash to double hyphen",
    does: "rewrites em dashes as -- for plain-text targets",
    find: "—",
    flags: "g",
    replace: "--",
    phases: ["output"],
    before: "She paused—thinking carefully—before answering.",
    after: "She paused--thinking carefully--before answering.",
  },
  {
    id: "double-hyphen-to-em-dash",
    category: "formatting",
    name: "Double hyphen to em dash",
    does: "rewrites -- as a proper em dash",
    find: "--",
    flags: "g",
    replace: "—",
    phases: ["output"],
    before: "She paused--thinking carefully--before answering.",
    after: "She paused—thinking carefully—before answering.",
  },
  {
    id: "exclamation-to-period",
    category: "style",
    name: "Calm the exclamations",
    does: "squeezes runs of !!! down to a single !",
    find: "!{2,}",
    flags: "g",
    replace: "!",
    phases: ["output"],
    before: "Amazing!!! I love it!!!!",
    after: "Amazing! I love it!",
  },
  {
    id: "ellipsis-normalization",
    category: "style",
    name: "Tidy ellipses",
    does: "turns any run of dots into one proper ellipsis character",
    find: "\\.{2,}|…+",
    flags: "g",
    replace: "…",
    phases: ["output"],
    before: "Well.... I suppose..... maybe....",
    after: "Well… I suppose… maybe…",
  },
  {
    id: "remove-double-spaces",
    category: "style",
    name: "Single spaces only",
    does: "collapses runs of spaces down to one",
    find: " {2,}",
    flags: "g",
    replace: " ",
    phases: ["output"],
    before: "Hello  world.   How  are  you?",
    after: "Hello world. How are you?",
  },
  {
    id: "strip-markdown-bold",
    category: "compatibility",
    name: "Strip bold marks",
    does: "removes **bold** markers, keeps the words",
    find: "\\*\\*([^*]+)\\*\\*",
    flags: "g",
    replace: "$1",
    phases: ["output"],
    before: "This is **very important** text.",
    after: "This is very important text.",
  },
  {
    id: "strip-all-markdown",
    category: "compatibility",
    name: "Strip all markdown",
    does: "removes bold, italic, underscore and code markers in one pass",
    find: "\\*\\*([^*]+)\\*\\*|\\*([^*]+)\\*|_([^_]+)_|`([^`]+)`",
    flags: "g",
    replace: "$1$2$3$4",
    phases: ["output"],
    before: "This is **bold**, *italic*, and `code`.",
    after: "This is bold, italic, and code.",
  },
  {
    id: "normalize-line-endings",
    category: "compatibility",
    name: "Fix Windows line endings",
    does: "converts CRLF line endings to plain LF",
    find: "\\r\\n",
    flags: "g",
    replace: "\n",
    phases: ["output"],
    before: "Line one\r\nLine two\r\nLine three",
    after: "Line one\nLine two\nLine three",
  },
  {
    id: "remove-ai-apologies",
    category: "guardrails",
    name: "Remove assistant apologies",
    does: "deletes \"I apologize\" / \"As an AI\" phrases that break the scene",
    find: "\\b(I apologize|I'm sorry|As an AI|I cannot|I'm not able to|I don't have the ability)\\b[^.!?]*[.!?]?\\s*",
    flags: "gi",
    replace: "",
    phases: ["output"],
    before: "I apologize, but I cannot help with that. However, I can suggest...",
    after: "However, I can suggest...",
  },
  {
    id: "remove-empty-quotes",
    category: "cleanup",
    name: "Remove empty quotes",
    does: "deletes leftover empty quotation marks",
    find: "\"\\s*\"|''|\"\"",
    flags: "g",
    replace: "",
    phases: ["output"],
    before: "She said \"\" and walked away. He replied ''.",
    after: "She said  and walked away. He replied .",
  },
  {
    id: "remove-thinking-tags",
    category: "guardrails",
    name: "Remove thinking tags",
    does: "deletes <thinking> blocks and [internal] asides the model leaks",
    find: "<thinking>[\\s\\S]*?</thinking>|<internal>[\\s\\S]*?</internal>|\\[thinking\\][\\s\\S]*?\\[/thinking\\]|\\[internal\\][\\s\\S]*?\\[/internal\\]",
    flags: "gi",
    replace: "",
    phases: ["output"],
    before: "<thinking>I should be careful here</thinking>Hello there!",
    after: "Hello there!",
  },
  {
    id: "remove-system-artifacts",
    category: "guardrails",
    name: "Remove prompt leakage",
    does: "deletes [INST], <<SYS>> and similar system markers that leak into replies",
    find: "\\[INST\\]|\\[/INST\\]|<<SYS>>|<</SYS>>|<\\|im_start\\|>|<\\|im_end\\|>|<\\|user\\|>|<\\|assistant\\|>",
    flags: "gi",
    replace: "",
    phases: ["output"],
    before: "[INST] Hello [/INST] Hi there! <|im_end|>",
    after: " Hello  Hi there! ",
  },
  {
    id: "clean-repeated-words",
    category: "cleanup",
    name: "Fix doubled words",
    does: "collapses accidentally repeated repeated words to one",
    find: "\\b(\\w+)\\s+\\1\\b",
    flags: "gi",
    replace: "$1",
    phases: ["output"],
    before: "She walked walked to the the store store.",
    after: "She walked to the store.",
  },
  {
    id: "remove-scene-directions",
    category: "cleanup",
    name: "Remove scene directions",
    does: "drops [Scene:], [Location:], [Time:] style stage notes",
    find: "\\[(?:Scene|Location|Time|Setting|Mood|Music|Atmosphere|Note|Author|AN)[:\\s][^\\]]*\\]",
    flags: "gi",
    replace: "",
    phases: ["output"],
    before: "[Scene: A dark forest] The path wound through the trees. [Mood: Tense]",
    after: " The path wound through the trees. ",
  },
  {
    id: "highlight-dialogue",
    category: "roleplay",
    name: "Color the dialogue",
    does: "wraps spoken lines in a color tag, for apps that render HTML in replies",
    find: "\"([^\"]+)\"",
    flags: "g",
    replace: "<span style=\"color:#6ee7b7\">\"$1\"</span>",
    phases: ["display"],
    before: "\"Hello,\" she said. \"How are you?\"",
    after: "<span style=\"color:#6ee7b7\">\"Hello,\"</span> she said. <span style=\"color:#6ee7b7\">\"How are you?\"</span>",
  },
  {
    id: "remove-narrator-voice",
    category: "cleanup",
    name: "Remove narrator tags",
    does: "drops [Narrator] and *Narrator:* markers before lines",
    find: "\\[Narrator\\][:\\s]*|\\*Narrator[:\\s]*\\*|Narrator[:\\s]+",
    flags: "gi",
    replace: "",
    phases: ["output"],
    before: "[Narrator] The sun set slowly. *Narrator:* Time passed.",
    after: "The sun set slowly.  Time passed.",
  },
  {
    id: "smart-quotes",
    category: "formatting",
    name: "Curl straight quotes",
    does: "curls \"these\" into proper typographic quotes on display",
    find: "\"([^\"]*)\"",
    flags: "g",
    replace: "“$1”",
    phases: ["display"],
    before: "\"Hello,\" she said.",
    after: "“Hello,” she said.",
  },
  {
    id: "add-paragraph-breaks",
    category: "formatting",
    name: "Break after dialogue",
    does: "starts a new paragraph when narration follows a spoken line",
    find: "([.!?]\")\\s+([A-Z])",
    flags: "g",
    replace: "$1\n\n$2",
    phases: ["output"],
    before: "\"I understand.\" She nodded slowly.",
    after: "\"I understand.\"\n\nShe nodded slowly.",
  },
  {
    id: "remove-filler-words",
    category: "style",
    name: "Cut filler words",
    does: "removes just, really, very and friends (edit the list to taste)",
    find: "\\b(just|really|very|actually|basically|literally|simply|definitely|certainly)\\s+",
    flags: "gi",
    replace: "",
    phases: ["output"],
    before: "I just really wanted to say that I very much appreciate this.",
    after: "I wanted to say that I much appreciate this.",
  },
  {
    id: "convert-contractions",
    category: "style",
    name: "Expand don't to do not",
    does: "expands the contraction for a more formal voice (copy it for others)",
    find: "\\bdon't\\b",
    flags: "gi",
    replace: "do not",
    phases: ["output"],
    before: "I don't think we should.",
    after: "I do not think we should.",
  },
  {
    id: "casual-contractions",
    category: "style",
    name: "Contract do not to don't",
    does: "the casual twin - contracts the phrase (copy it for others)",
    find: "\\bdo not\\b",
    flags: "gi",
    replace: "don't",
    phases: ["output"],
    before: "I do not think we should.",
    after: "I don't think we should.",
  },
  {
    id: "strip-html-tags",
    category: "compatibility",
    name: "Strip HTML tags",
    does: "removes every <tag>, keeps the text between them",
    find: "<[^>]+>",
    flags: "g",
    replace: "",
    phases: ["output"],
    before: "<p>Hello <strong>world</strong>!</p>",
    after: "Hello world!",
  },
  {
    id: "unicode-to-ascii",
    category: "compatibility",
    name: "Arrows to ASCII",
    does: "rewrites the Unicode right arrow as ->",
    find: "→",
    flags: "g",
    replace: "->",
    phases: ["output"],
    before: "Go left → then right ← and up ↑",
    after: "Go left -> then right ← and up ↑",
  },
  {
    id: "remove-zero-width",
    category: "compatibility",
    name: "Remove invisible characters",
    does: "deletes zero-width characters that break matching and copy-paste",
    find: "[\\u200B-\\u200D\\uFEFF\\u00AD]",
    flags: "g",
    replace: "",
    phases: ["output"],
    before: "Hello​world‌!",
    after: "Helloworld!",
  },
  {
    id: "sillytavern-macro-user",
    category: "roleplay",
    name: "Fill in {{user}}",
    does: "swaps the {{user}} placeholder for a name - edit the replacement first",
    find: "\\{\\{user\\}\\}",
    flags: "gi",
    replace: "Player",
    phases: ["output"],
    before: "{{user}} walked into the room.",
    after: "Player walked into the room.",
  },
  {
    id: "sillytavern-macro-char",
    category: "roleplay",
    name: "Fill in {{char}}",
    does: "swaps the {{char}} placeholder for a name - edit the replacement first",
    find: "\\{\\{char\\}\\}",
    flags: "gi",
    replace: "Character",
    phases: ["output"],
    before: "{{char}} smiled warmly.",
    after: "Character smiled warmly.",
  },
  {
    id: "timestamp-remover",
    category: "cleanup",
    name: "Remove timestamps",
    does: "deletes 12:34 and [12:34:56 PM] style clock stamps",
    find: "\\[?\\d{1,2}[:\\/]\\d{2}(?:[:\\/]\\d{2})?(?:\\s*[AP]M)?\\]?|\\d{4}-\\d{2}-\\d{2}",
    flags: "gi",
    replace: "",
    phases: ["output"],
    before: "[10:30 AM] Hello! Today is 2024-01-15.",
    after: " Hello! Today is .",
  },
  {
    id: "remove-bracket-text",
    category: "cleanup",
    name: "Remove text in brackets",
    does: "drops [anything like this] from the reply",
    find: "\\s?\\[[^\\]\\n]*\\]",
    flags: "g",
    replace: "",
    phases: ["output"],
    before: "Sure! [thinking about it] Let's go.",
    after: "Sure! Let's go.",
  },
  {
    id: "stop-speaking-for-me",
    category: "guardrails",
    name: "Stop speaking for me",
    does: "cuts the reply the moment it starts writing your line",
    find: "\\s?\\bYou:[\\s\\S]*$",
    flags: "",
    replace: "",
    phases: ["output"],
    before: "...he grins. You: \"I guess-\"",
    after: "...he grins.",
  },
];
