/**
 * Build Vaude.exe - real software from the same code the CLI runs.
 * 1. Bake the UI assets (index/tokens/boot + every discovered app bundle + manifests) into
 *    src/generated/packaged-assets.ts.
 * 2. Bake a STATIC format registry into src/generated/packaged-formats.ts (a compiled binary cannot
 *    glob; the generator preserves drop-in truth by regenerating from the folder scan every build).
 * 3. bun build --compile src/desktop.ts -> dist/Vaude.exe with the beam-V icon, console hidden.
 * Run: bun run scripts/build-desktop.ts
 */
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const uiDir = join(root, "src", "ui");
const genDir = join(root, "src", "generated");
await mkdir(genDir, { recursive: true });

// -- 1. UI assets -----------------------------------------------------------------------------------

/** The react family stays OUT of every app/boot bundle; the page's import map resolves these to
 * the single /vendor copies (one React per page - two copies crash hooks with a null dispatcher). */
const REACT_EXTERNALS = ["react", "react/jsx-runtime", "react-dom/client", "react-dom"];

async function bundleBrowser(entry: string, external: string[] = REACT_EXTERNALS): Promise<string> {
  const built = await Bun.build({ entrypoints: [entry], target: "browser", format: "esm", external });
  if (!built.success) throw new Error(`bundle failed for ${entry}: ${built.logs.map((l) => l.message).join("; ")}`);
  return built.outputs[0]!.text();
}

/** name -> entry stub + externals: react itself bundles fully; the other two link against it. */
const VENDOR_SPECS: Record<string, { entry: string; external: string[] }> = {
  react: { entry: "vendor/react.ts", external: [] },
  "jsx-runtime": { entry: "vendor/jsx-runtime.ts", external: ["react"] },
  "jsx-dev-runtime": { entry: "vendor/jsx-dev-runtime.ts", external: ["react"] },
  "react-dom-client": { entry: "vendor/react-dom-client.ts", external: ["react", "react/jsx-runtime"] },
};

const appsGlob = new Bun.Glob("*/index.{ts,tsx}");
const appIds: string[] = [];
const apps: Record<string, string> = {};
const manifests: unknown[] = [];
for await (const rel of appsGlob.scan({ cwd: join(uiDir, "apps") })) {
  const id = rel.split(/[\\/]/)[0]!;
  if (id.startsWith("_")) continue;
  appIds.push(id);
  const entry = join(uiDir, "apps", rel);
  apps[id] = await bundleBrowser(entry);
  const mod = (await import(entry)) as { default?: { manifest?: unknown } };
  if (mod.default?.manifest) manifests.push(mod.default.manifest);
}

const stepsGlob = new Bun.Glob("*/index.{ts,tsx}");
const stepIds: string[] = [];
const setupSteps: Record<string, string> = {};
for await (const rel of stepsGlob.scan({ cwd: join(uiDir, "setup", "steps") })) {
  const id = rel.split(/[\\/]/)[0]!;
  if (id.startsWith("_")) continue;
  stepIds.push(id);
  setupSteps[id] = await bundleBrowser(join(uiDir, "setup", "steps", rel));
}

const vendor: Record<string, string> = {};
for (const [name, spec] of Object.entries(VENDOR_SPECS)) {
  vendor[name] = await bundleBrowser(join(uiDir, spec.entry), spec.external);
}

const assets = {
  indexHtml: await Bun.file(join(uiDir, "index.html")).text(),
  tokensCss: await Bun.file(join(uiDir, "theme", "tokens.css")).text(),
  bootJs: await bundleBrowser(join(uiDir, "boot.ts")),
  vendor,
  faviconIcoB64: Buffer.from(await Bun.file(join(root, "build", "vaude.ico")).arrayBuffer()).toString("base64"),
  iconPngB64: Buffer.from(await Bun.file(join(root, "build", "vaude-256.png")).arrayBuffer()).toString("base64"),
  apps,
  manifests,
  setupSteps,
};
await Bun.write(
  join(genDir, "packaged-assets.ts"),
  `/** GENERATED by scripts/build-desktop.ts - do not edit. */\n` +
    `import type { PackagedAssets } from "../ui/assets";\n` +
    `export const PACKAGED_ASSETS: PackagedAssets = ${JSON.stringify(assets)};\n`,
);
console.log(`baked ui assets (${appIds.length} apps: ${appIds.join(", ")}; ${stepIds.length} setup steps: ${stepIds.join(", ")})`);

// -- 1b. BOOT SMOKE: the build proves the page can boot before anyone claims done -------------------
// Three first-boot crashes taught this: tsc + tests never exercise module RESOLUTION in the page.
// So the build (a) EXECUTES each vendor bundle and asserts the named exports the app relies on,
// and (b) asserts every bare import in every baked bundle has an import-map entry. Fail = no exe.
const REQUIRED_VENDOR_EXPORTS: Record<string, string[]> = {
  react: ["createElement", "useState", "useEffect"],
  "jsx-runtime": ["jsx", "jsxs", "Fragment"],
  "jsx-dev-runtime": ["jsxDEV", "Fragment"],
  "react-dom-client": ["createRoot"],
};
const importMapMatch = /<script type="importmap">\s*([\s\S]*?)<\/script>/.exec(assets.indexHtml);
if (!importMapMatch) throw new Error("smoke: index.html carries no import map");
const importMapKeys = Object.keys((JSON.parse(importMapMatch[1]!) as { imports: Record<string, string> }).imports);

const smokeDir = join(root, "dist", ".smoke");
await mkdir(smokeDir, { recursive: true });
for (const [name, wanted] of Object.entries(REQUIRED_VENDOR_EXPORTS)) {
  const file = join(smokeDir, `${name}.mjs`);
  await Bun.write(file, vendor[name]!);
  const mod = (await import(pathToFileURL(file).href)) as Record<string, unknown>;
  const missing = wanted.filter((exp) => mod[exp] === undefined);
  if (missing.length) {
    throw new Error(`smoke: /vendor/${name}.js lacks export(s) ${missing.join(", ")} - the page would crash at boot`);
  }
}

const bareSpecifiers = (code: string): string[] => {
  const out = new Set<string>();
  const re = /from\s*["']([^"'\n]+)["']|import\s*\(\s*["']([^"'\n]+)["']\s*\)/g;
  for (let m = re.exec(code); m; m = re.exec(code)) {
    const spec = (m[1] ?? m[2])!;
    if (spec.startsWith("./") || spec.startsWith("../") || spec.startsWith("/") || spec.startsWith("http")) continue;
    if (!/^[@\w][\w@/.-]*$/.test(spec)) continue; // module-shaped only: skips prose/concat inside bundled strings
    out.add(spec);
  }
  return [...out];
};
const allBundles: Record<string, string> = {
  boot: assets.bootJs,
  ...Object.fromEntries(Object.entries(apps).map(([k, v]) => [`app:${k}`, v])),
  ...Object.fromEntries(Object.entries(setupSteps).map(([k, v]) => [`step:${k}`, v])),
  ...Object.fromEntries(Object.entries(vendor).map(([k, v]) => [`vendor:${k}`, v])),
};
for (const [name, code] of Object.entries(allBundles)) {
  const uncovered = bareSpecifiers(code).filter((s) => !importMapKeys.includes(s));
  if (uncovered.length) {
    throw new Error(`smoke: bundle "${name}" imports bare ${uncovered.join(", ")} with no import-map entry - the page would crash at boot`);
  }
}
console.log(`boot smoke passed (${Object.keys(REQUIRED_VENDOR_EXPORTS).length} vendor graphs executed, ${Object.keys(allBundles).length} bundles resolution-checked)`);

// -- 2. static format registry ----------------------------------------------------------------------

const formatsGlob = new Bun.Glob("*/index.ts");
const formatIds: string[] = [];
for await (const rel of formatsGlob.scan({ cwd: join(root, "src", "formats") })) {
  const id = rel.split(/[\\/]/)[0]!;
  if (id.startsWith("_")) continue;
  formatIds.push(id);
}
formatIds.sort();
const importLines = formatIds.map((id, i) => `import f${i} from "../formats/${id}/index";`).join("\n");
const registerLines = formatIds
  .map((_, i) => `  for (const a of Array.isArray(f${i}) ? f${i} : [f${i}]) registry.register(a);`)
  .join("\n");
await Bun.write(
  join(genDir, "packaged-formats.ts"),
  `/** GENERATED by scripts/build-desktop.ts - do not edit. Static registry for the compiled exe. */\n` +
    `import { registry } from "../core";\n${importLines}\n\n` +
    `export function registerPackagedFormats(): void {\n${registerLines}\n}\n`,
);
console.log(`baked static format registry (${formatIds.length} families: ${formatIds.join(", ")})`);

// -- 3. compile -------------------------------------------------------------------------------------

await mkdir(join(root, "dist"), { recursive: true });
const compile = Bun.spawnSync(
  [
    "bun", "build", "--compile",
    join(root, "src", "desktop.ts"),
    "--outfile", join(root, "dist", "Vaude.exe"),
    `--windows-icon=${join(root, "build", "vaude.ico")}`,
    "--windows-hide-console",
  ],
  { cwd: root, stdout: "inherit", stderr: "inherit" },
);
if (compile.exitCode !== 0) throw new Error("compile failed");
console.log("dist/Vaude.exe ready");
