/**
 * Generate the browser-safe capability import seam from entity and format drop-in folders.
 *
 * Run:   bun run scripts/capability-manifest.ts
 * Check: bun run scripts/capability-manifest.ts --check
 */
import {
  existsSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import {
  basename,
  dirname,
  join,
  relative,
} from "node:path";

const ROOT = join(import.meta.dir, "..");
const ROOTS = [join(ROOT, "src", "entities"), join(ROOT, "src", "formats")];
const OUTPUT = join(
  ROOT,
  "src",
  "ui",
  "apps",
  "workbench",
  "capabilities",
  "generated.ts",
);
const CHECK_ONLY = process.argv.includes("--check");
const INFRA = new Set([
  "catalog.ts",
  "descriptor.ts",
  "exposure.ts",
  "index.ts",
  "navigation.ts",
  "operations.ts",
  "search.ts",
  "shared.ts",
  "types.ts",
]);

const toPosix = (path: string): string => path.split("\\").join("/");
const isCapabilityFile = (name: string): boolean =>
  name.endsWith(".ts")
  && !name.endsWith(".test.ts")
  && !name.startsWith("_")
  && !INFRA.has(name);

function collectCapabilityFiles(root: string): string[] {
  const files: string[] = [];
  const visit = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) visit(path);
      else if (basename(dir) === "capabilities" && isCapabilityFile(entry.name)) {
        files.push(path);
      }
    }
  };
  visit(root);
  return files;
}

function modulePath(file: string): string {
  const withoutExtension = file.replace(/\.ts$/, "");
  const path = toPosix(relative(dirname(OUTPUT), withoutExtension));
  return path.startsWith(".") ? path : `./${path}`;
}

function render(files: readonly string[]): string {
  const imports = files.map(
    (file, index) => `import capabilityModule${index} from "${modulePath(file)}";`,
  );
  const names = files.map((_, index) => `  capabilityModule${index},`);
  return `/**
 * Generated browser capability import seam. Run \`bun run capabilities\` to update it.
 * Do not edit this file by hand; capability folders are the source of truth.
 */
import type { ContentCapability } from "../../../../entities/capabilities";
${imports.join("\n")}

const capabilityModules: readonly unknown[] = [
${names.join("\n")}
];

/** Every browser-visible semantic capability, generated from the drop-in folders. */
export const workbenchCapabilities = capabilityModules.flatMap((entry): readonly unknown[] =>
  Array.isArray(entry) ? entry : [entry],
) as readonly ContentCapability[];
`;
}

const files = ROOTS.flatMap(collectCapabilityFiles)
  .sort((a, b) => toPosix(a).localeCompare(toPosix(b)));
const body = render(files);

if (CHECK_ONLY) {
  const existing = existsSync(OUTPUT) ? readFileSync(OUTPUT, "utf8") : "";
  if (existing !== body) {
    console.error("capabilities:check: generated capability manifest is stale");
    console.error("capabilities:check: run `bun run capabilities` and commit the result");
    process.exit(1);
  }
  console.log(`capabilities:check: ${files.length} capability modules are current`);
} else {
  writeFileSync(OUTPUT, body, "utf8");
  console.log(`capabilities: wrote ${files.length} capability modules`);
}
