/**
 * Emit docs/generated/fields.<kind>.json from the live entity schemas (src/entities/<kind>/schema.ts).
 * The schema's own JSDoc is the source of truth for each field's meaning and its producing formats,
 * so the reference docs' field tables are GENERATED, never hand-transcribed (no field name or type is
 * ever authored by hand). To improve a field's documented meaning, improve the JSDoc in schema.ts and
 * re-run this; the docs follow. Same docs-as-code contract as scripts/format-matrix.ts.
 *
 * Run:   bun run scripts/docs-fields.ts
 * Check: bun run scripts/docs-fields.ts --check   (fail if committed JSON differs)
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import ts from "typescript";

const ENTITIES = ["character", "lorebook", "persona", "preset", "regex", "pack"] as const;
type Kind = (typeof ENTITIES)[number];

// Producer tokens as they actually appear in the schema JSDoc (parenthetical provenance hints).
const PRODUCERS = [
  "CCv3",
  "CCv2/v3",
  "CCv2",
  "RC",
  "RoleCall",
  "SillyTavern",
  "ST",
  "Risu",
  "Agnai",
  "Backyard",
  "Faraday",
  "NovelAI",
  "Pygmalion",
  "Lumiverse",
  "Marinara",
] as const;

interface FieldDoc {
  name: string;
  optional: boolean;
  type: string;
  meaning: string;
  producers: string[];
}
interface ShapeDoc {
  name: string;
  doc: string;
  kind: "interface" | "type";
  fields: FieldDoc[];
}
interface EntityFields {
  kind: Kind;
  source: string;
  shapes: ShapeDoc[];
}

/** Flatten a JSDoc comment (string | NodeArray of comment parts) to plain text. */
const commentText = (c: string | ts.NodeArray<ts.JSDocComment> | undefined): string => {
  if (!c) return "";
  if (typeof c === "string") return c;
  return c.map((part) => part.text).join("");
};

/** The JSDoc block(s) immediately above a node, joined and whitespace-normalised. */
const jsdocOf = (node: ts.Node): string => {
  const docs = (node as { jsDoc?: ts.JSDoc[] }).jsDoc;
  if (!docs || docs.length === 0) return "";
  return docs
    .map((d) => commentText(d.comment))
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
};

/** Producer tokens named in a field's meaning text; longest-match-first, de-duped, stable order. */
const producersIn = (meaning: string): string[] => {
  const hits = new Set<string>();
  for (const p of PRODUCERS) {
    // word-ish boundary so "ST" doesn't match inside "instructions"
    const re = new RegExp(`(^|[^A-Za-z])${p.replace(/[/]/g, "\\/")}([^A-Za-z]|$)`);
    if (re.test(meaning)) hits.add(p);
  }
  // collapse CCv2 + CCv2/v3 overlap: if the combined tag is present, drop the bare CCv2
  if (hits.has("CCv2/v3")) hits.delete("CCv2");
  if (hits.has("RoleCall")) hits.delete("RC");
  return [...hits];
};

const memberToField = (m: ts.PropertySignature): FieldDoc | null => {
  if (!m.name || !ts.isIdentifier(m.name)) {
    // string-index or computed members are not first-class documented fields
    if (m.name && ts.isStringLiteral(m.name)) {
      // keep quoted keys
    } else {
      return null;
    }
  }
  const name = m.name.getText();
  const meaning = jsdocOf(m);
  return {
    name,
    optional: !!m.questionToken,
    type: m.type ? m.type.getText().replace(/\s+/g, " ").trim() : "unknown",
    meaning,
    producers: producersIn(meaning),
  };
};

const shapeFromMembers = (
  name: string,
  doc: string,
  kind: "interface" | "type",
  members: ts.NodeArray<ts.TypeElement>,
): ShapeDoc => ({
  name,
  doc,
  kind,
  fields: members
    .filter(ts.isPropertySignature)
    .map(memberToField)
    .filter((f): f is FieldDoc => f !== null),
});

function extractShapes(sourceText: string, fileName: string): ShapeDoc[] {
  const sf = ts.createSourceFile(fileName, sourceText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const shapes: ShapeDoc[] = [];
  for (const stmt of sf.statements) {
    if (ts.isInterfaceDeclaration(stmt)) {
      shapes.push(shapeFromMembers(stmt.name.text, jsdocOf(stmt), "interface", stmt.members));
    } else if (ts.isTypeAliasDeclaration(stmt) && ts.isTypeLiteralNode(stmt.type)) {
      shapes.push(shapeFromMembers(stmt.name.text, jsdocOf(stmt), "type", stmt.type.members));
    }
  }
  return shapes;
}

/** Escape a cell so pipes and newlines in a type or meaning never break the table. */
const cell = (s: string): string => s.replace(/\|/g, "\\|").replace(/\n/g, " ").trim();

/** Render one entity's shapes as embeddable markdown field tables (the canonical table shape every
 * entity reference doc uses; agents paste these, they do not transcribe field names or types). A blank
 * Meaning means the schema JSDoc did not document it: fill it in the doc prose, do not invent a type. */
function renderFieldsMarkdown(e: EntityFields): string {
  const lines: string[] = [
    `<!-- GENERATED by scripts/docs-fields.ts from ${e.source} - do not edit field/type/producer cells by hand -->`,
    "",
  ];
  for (const s of e.shapes) {
    lines.push(`### \`${s.name}\``, "");
    const rows = s.fields.map((f) => {
      const name = `\`${f.name}${f.optional ? "?" : ""}\``;
      const type = `\`${cell(f.type)}\``;
      const prod = f.producers.length ? f.producers.join(", ") : "-";
      return `| ${name} | ${type} | ${prod} | ${cell(f.meaning)} |`;
    });
    lines.push("| Field | Type | Producers | Meaning |", "| --- | --- | --- | --- |", ...rows, "");
  }
  return lines.join("\n");
}

const outDir = join(import.meta.dir, "../docs/generated");
const checkOnly = process.argv.includes("--check");

let stale = false;
const summary: string[] = [];

for (const kind of ENTITIES) {
  const src = `src/entities/${kind}/schema.ts`;
  const abs = join(import.meta.dir, "..", src);
  if (!existsSync(abs)) {
    summary.push(`${kind}: no schema.ts (skipped)`);
    continue;
  }
  const shapes = extractShapes(readFileSync(abs, "utf8"), abs);
  const payload: EntityFields = { kind, source: src, shapes };
  const fieldCount = shapes.reduce((n, s) => n + s.fields.length, 0);
  // Two artifacts per entity: the JSON (machine-readable, for the future doc/agent index) and the
  // markdown field tables (embeddable in the reference doc so agents paste, never transcribe).
  const artifacts: Array<[string, string]> = [
    [`fields.${kind}.json`, JSON.stringify(payload, null, 2) + "\n"],
    [`fields.${kind}.md`, renderFieldsMarkdown(payload) + "\n"],
  ];

  for (const [file, body] of artifacts) {
    const outPath = join(outDir, file);
    if (checkOnly) {
      let existing = "";
      try {
        existing = readFileSync(outPath, "utf8");
      } catch {
        console.error(`docs-fields:check: missing ${outPath}`);
        stale = true;
        continue;
      }
      if (existing !== body) {
        console.error(`docs-fields:check: docs/generated/${file} is stale`);
        stale = true;
      }
    } else {
      mkdirSync(outDir, { recursive: true });
      writeFileSync(outPath, body, "utf8");
    }
  }
  summary.push(`${kind}: ${shapes.length} shapes, ${fieldCount} fields`);
}

if (checkOnly) {
  if (stale) {
    console.error("docs-fields:check: run `bun run scripts/docs-fields.ts` and commit.");
    process.exit(1);
  }
  console.log("docs-fields:check: generated field docs are current");
} else {
  console.log("wrote docs/generated/fields.*.json\n" + summary.join("\n"));
}
