/** Generate the static format registry required by compiled and browser-only builds. */
import { join } from "node:path";

export async function bakeFormatRegistry(root: string): Promise<string[]> {
  const glob = new Bun.Glob("*/index.ts");
  const ids: string[] = [];
  for await (const relative of glob.scan({ cwd: join(root, "src", "formats") })) {
    const id = relative.split(/[\\/]/)[0]!;
    if (!id.startsWith("_")) ids.push(id);
  }
  ids.sort();
  const imports = ids.map((id, index) => `import f${index} from "../formats/${id}/index";`).join("\n");
  const registers = ids
    .map((_, index) => `  for (const a of Array.isArray(f${index}) ? f${index} : [f${index}]) registry.register(a);`)
    .join("\n");
  await Bun.write(
    join(root, "src", "generated", "packaged-formats.ts"),
    `/** GENERATED by a build script - do not edit. Static registry for closed build graphs. */\n` +
      `import * as registry from "../core/registry";\n${imports}\n\n` +
      `export function registerPackagedFormats(): void {\n${registers}\n}\n`,
  );
  return ids;
}
