/**
 * RisuAI's macro catalog (CBS), GENERATED from that engine's own documentation.
 *
 * DO NOT EDIT BY HAND. Regenerate with:
 *   bun run scripts/risu-macros.ts --risu-root=<a RisuAI checkout>
 *
 * Source: src/etc/docs/cbs_docs.cbs at RisuAI 72ce721878d65b09baf4339638dfd221d1788261
 * Read 142 macros (from 143 documented rows).
 *
 * WHY THIS ONE IS GENERATED AND THE OTHERS ARE NOT. RisuAI publishes a machine-readable CSV of its
 * own macros; SillyTavern, RoleCall, Marinara and Lumiverse do not, so those catalogs were read out
 * of prose and source by hand. Where a list exists, retyping it is 170 chances to invent a macro.
 *
 * TWO HONEST LIMITS, both consequences of what the source carries.
 *
 * NO GROUPS. The CSV has no categories, so everything is one group rather than a hand-invented
 * taxonomy - grouping 170 entries by eye would be organisation this file cannot support, and the
 * reference is searchable instead.
 *
 * NO OPERATION ANNOTATIONS. MacroEntry.op is what lets the hub compute cross-engine equivalence and
 * collisions, and nothing in the CSV maps to one; they have to be added by reading the parser, per
 * entry, where a name would otherwise lie. Until they exist Risu is a REFERENCE here and not a
 * translation target - see macroGroupsForDialect. The known worklist is the set of names Risu shares
 * with Lumiverse while meaning something else.
 */
import type { MacroGroup } from "./types";

export const RISU_MACRO_GROUPS: MacroGroup[] = [
  {
    name: "All CBS macros",
    description:
      "Every macro RisuAI documents, as its own CBS reference lists them. Risu writes examples as "
      + "[[name]] so its documentation is not itself parsed; the engine reads {{name}}.",
    macros: [
      { macro: "{{previous_char_chat}}", description: "Returns the previous character message", aliases: ["previouscharchat", "lastcharmessage"] },
      { macro: "{{previous_user_chat}}", description: "Returns the previous user message", aliases: ["previoususerchat", "lastusermessage"] },
      { macro: "{{char}}", description: "Returns the character's name or nickname", aliases: ["bot"] },
      { macro: "{{user}}", description: "Returns the user's name" },
      { macro: "{{personality}}", description: "Returns the character's personality", aliases: ["char_persona", "charpersona"] },
      { macro: "{{description}}", description: "Returns the character's description", aliases: ["char_desc", "chardesc"] },
      { macro: "{{scenario}}", description: "Returns the character's scenario" },
      { macro: "{{example_dialogue}}", description: "Returns the character's example dialogue", aliases: ["example_message", "exampledialogue", "examplemessage"] },
      { macro: "{{persona}}", description: "Returns the user's persona", aliases: ["user_persona", "userpersona"] },
      { macro: "{{main_prompt}}", description: "Returns the main/system prompt", aliases: ["system_prompt", "systemprompt", "mainprompt"] },
      { macro: "{{lorebook}}", description: "Returns the lorebook/world info", aliases: ["world_info", "worldinfo"] },
      { macro: "{{history}}", description: "Returns the full chat history", aliases: ["messages"] },
      { macro: "{{user_history}}", description: "Returns the user's message history", aliases: ["user_messages", "userhistory", "usermessages"] },
      { macro: "{{char_history}}", description: "Returns the character's message history", aliases: ["char_messages", "charhistory", "charmessages"] },
      { macro: "{{ujb}}", description: "Returns the global/system note", aliases: ["global_note", "system_note", "globalnote", "systemnote"] },
      { macro: "{{chat_index}}", description: "Returns the current chat index", aliases: ["chatindex"] },
      { macro: "{{first_msg_index}}", description: "Returns the first message index", aliases: ["firstmessageindex", "firstmsgindex"] },
      { macro: "{{blank}}", description: "Returns an empty string", aliases: ["none"] },
      { macro: "{{message_time}}", description: "Returns the time of the message", aliases: ["messagetime"] },
      { macro: "{{message_date}}", description: "Returns the date of the message", aliases: ["messagedate"] },
      { macro: "{{message_unixtime_array}}", description: "Returns an array of message unix times", aliases: ["messageunixtimearray"] },
      { macro: "{{unixtime}}", description: "Returns the current unix time" },
      { macro: "{{time}}", description: "Returns the current time" },
      { macro: "{{date}}", description: "Returns the current date" },
      { macro: "{{isotime}}", description: "Returns the current UTC time" },
      { macro: "{{isodate}}", description: "Returns the current UTC date" },
      { macro: "{{message_idle_duration}}", description: "Returns idle duration between last two user messages", aliases: ["messageidleduration"] },
      { macro: "{{idle_duration}}", description: "Returns idle duration since last message", aliases: ["idleduration"] },
      { macro: "{{br}}", description: "Returns a newline character", aliases: ["newline"] },
      { macro: "{{model}}", description: "Returns the current AI model" },
      { macro: "{{axmodel}}", description: "Returns the submodel" },
      { macro: "{{role}}", description: "Returns the message role" },
      { macro: "{{isfirstmsg}}", description: "Returns 1 if first message, else 0", aliases: ["is_first_msg", "is_first_message", "isfirstmessage"] },
      { macro: "{{random}}", description: "Returns a random number" },
      { macro: "{{maxcontext}}", description: "Returns the max context value" },
      { macro: "{{lastmessage}}", description: "Returns the last message data" },
      { macro: "{{lastmessageid}}", description: "Returns the last message index", aliases: ["lastmessageindex"] },
      { macro: "{{emotionlist}}", description: "Returns the list of emotion names" },
      { macro: "{{assetlist}}", description: "Returns the list of asset names" },
      { macro: "{{prefill_supported}}", description: "Returns 1 if prefill is supported", aliases: ["prefillsupported", "prefill"] },
      { macro: "{{screen_width}}", description: "Returns the screen width", aliases: ["screenwidth"] },
      { macro: "{{screen_height}}", description: "Returns the screen height", aliases: ["screenheight"] },
      { macro: "{{cbr}}", description: "Returns a literal newline string", aliases: ["cnl", "cnewline"] },
      { macro: "{{decbo}}", description: "Returns a special open curly bracket character", aliases: ["displayescapedcurlybracketopen"] },
      { macro: "{{decbc}}", description: "Returns a special close curly bracket character", aliases: ["displayescapedcurlybracketclose"] },
      { macro: "{{bo}}", description: "Returns double open curly bracket character", aliases: ["ddecbo", "doubledisplayescapedcurlybracketopen"] },
      { macro: "{{bc}}", description: "Returns double close curly bracket character", aliases: ["ddecbc", "doubledisplayescapedcurlybracketclose"] },
      { macro: "{{tempvar::name}}", description: "Get a temporary variable", aliases: ["gettempvar"] },
      { macro: "{{settempvar::name::value}}", description: "Set a temporary variable" },
      { macro: "{{return::value}}", description: "Set a return value and force return" },
      { macro: "{{getvar::name}}", description: "Get a chat variable" },
      { macro: "{{calc::expression}}", description: "Calculate a string expression" },
      { macro: "{{addvar::name::value}}", description: "Add a value to a chat variable" },
      { macro: "{{setvar::name::value}}", description: "Set a chat variable" },
      { macro: "{{setdefaultvar::name::value}}", description: "Set a default value if variable is not set" },
      { macro: "{{getglobalvar::name}}", description: "Get a global chat variable" },
      { macro: "{{button::label::action}}", description: "Create a button" },
      { macro: "{{risu::size}}", description: "Insert a Risu logo image" },
      { macro: "{{equal::a::b}}", description: "Check if two values are equal" },
      { macro: "{{not_equal::a::b}}", description: "Check if two values are not equal", aliases: ["notequal"] },
      { macro: "{{greater::a::b}}", description: "Check if a > b" },
      { macro: "{{less::a::b}}", description: "Check if a < b" },
      { macro: "{{greater_equal::a::b}}", description: "Check if a >= b", aliases: ["greaterequal"] },
      { macro: "{{less_equal::a::b}}", description: "Check if a <= b", aliases: ["lessequal"] },
      { macro: "{{and::a::b}}", description: "Logical AND of two values" },
      { macro: "{{or::a::b}}", description: "Logical OR of two values" },
      { macro: "{{not::a}}", description: "Logical NOT of a value" },
      { macro: "{{file::name::base64data}}", description: "Display file or decode base64" },
      { macro: "{{startswith::string::prefix}}", description: "Check if a string starts with another" },
      { macro: "{{endswith::string::suffix}}", description: "Check if a string ends with another" },
      { macro: "{{contains::string::substring}}", description: "Check if a string contains another" },
      { macro: "{{replace::string::target::replacement}}", description: "Replace all occurrences in a string" },
      { macro: "{{split::string::delimiter}}", description: "Split a string into an array" },
      { macro: "{{join::array::delimiter}}", description: "Join an array into a string" },
      { macro: "{{spread::array}}", description: "Spread an array with :: separator" },
      { macro: "{{trim::string}}", description: "Trim whitespace from a string" },
      { macro: "{{length::string}}", description: "Get length of a string" },
      { macro: "{{arraylength::array}}", description: "Get length of an array", aliases: ["array_length"] },
      { macro: "{{lower::string}}", description: "Convert string to lowercase" },
      { macro: "{{upper::string}}", description: "Convert string to uppercase" },
      { macro: "{{capitalize::string}}", description: "Capitalize first letter" },
      { macro: "{{round::number}}", description: "Round a number" },
      { macro: "{{floor::number}}", description: "Floor a number" },
      { macro: "{{ceil::number}}", description: "Ceil a number" },
      { macro: "{{abs::number}}", description: "Absolute value" },
      { macro: "{{remaind::a::b}}", description: "Modulo operation" },
      { macro: "{{previous_chat_log::index}}", description: "Get previous chat log by index" },
      { macro: "{{tonumber::string}}", description: "Extract numbers from string" },
      { macro: "{{pow::base::exponent}}", description: "Power operation" },
      { macro: "{{arrayelement::array::index}}", description: "Get array element by index", aliases: ["array_element"] },
      { macro: "{{dictelement::dict::key}}", description: "Get dictionary/object element by key", aliases: ["dict_element", "objectelement", "object_element"] },
      { macro: "{{object_assert::dict::key::value}}", description: "Assert key in object", aliases: ["dict_assert", "dictassert", "objectassert"] },
      { macro: "{{element::json::key1::key2::...}}", description: "Get nested element from JSON", aliases: ["ele"] },
      { macro: "{{arrayshift::array}}", description: "Remove first element from array", aliases: ["array_shift"] },
      { macro: "{{arraypop::array}}", description: "Remove last element from array", aliases: ["array_pop"] },
      { macro: "{{arraypush::array::value}}", description: "Push value to array", aliases: ["array_push"] },
      { macro: "{{arraysplice::array::start::deleteCount::item}}", description: "Splice array", aliases: ["array_splice"] },
      { macro: "{{arrayassert::array::index::value}}", description: "Assert index in array", aliases: ["array_assert"] },
      { macro: "{{makearray::item1::item2::...}}", description: "Create array from arguments", aliases: ["array", "a", "make_array"] },
      { macro: "{{makedict::key1=value1::key2=value2::...}}", description: "Create dictionary/object from key=value pairs", aliases: ["dict", "d", "make_dict", "makeobject", "object", "o", "make_object"] },
      { macro: "{{range::start::end::step}}", description: "Create a range array" },
      { macro: "{{date::format::timestamp}}", description: "Format date/time", aliases: ["time", "datetimeformat", "date_time_format. format is a subset of Moment.js time format"] },
      { macro: "{{module_enabled::namespace}}", description: "Check if module is enabled", aliases: ["moduleenabled"] },
      { macro: "{{module_assetlist::namespace}}", description: "Get asset list from module", aliases: ["moduleassetlist"] },
      { macro: "{{filter::array::type}}", description: "Filter array. Type can be:\n- unique: Remove duplicates\n- nonempty: Remove empty values\n- all: do unique and nonempty" },
      { macro: "{{all::array::...}}", description: "Check if all values are 1" },
      { macro: "{{any::array::...}}", description: "Check if any value is 1" },
      { macro: "{{min::array::...}}", description: "Get minimum value" },
      { macro: "{{max::array::...}}", description: "Get maximum value" },
      { macro: "{{sum::array::...}}", description: "Sum values" },
      { macro: "{{average::array::...}}", description: "Average values" },
      { macro: "{{fixnum::number::decimals}}", description: "Fix number to decimals", aliases: ["fix_num", "fixnumber", "fix_number"] },
      { macro: "{{unicode_encode::string::index}}", description: "Get unicode code of char", aliases: ["unicodeencode"] },
      { macro: "{{unicode_decode::code}}", description: "Decode unicode code to char", aliases: ["unicodedecode"] },
      { macro: "{{u::hex}}", description: "Decode unicode from hex", aliases: ["unicodedecodefromhex"] },
      { macro: "{{ue::hex}}", description: "Encode unicode from hex", aliases: ["unicodeencodefromhex"] },
      { macro: "{{hash::string}}", description: "Hash a string" },
      { macro: "{{randint::min::max}}", description: "Random integer in range" },
      { macro: "{{dice::NdM}}", description: "Roll dice in NdM notation" },
      { macro: "{{fromhex::hex}}", description: "Convert hex to decimal" },
      { macro: "{{tohex::number}}", description: "Convert decimal to hex" },
      { macro: "{{metadata::key}}", description: "Get metadata value. argument can be:\n- mobile (is mobile)\n- local (is local)\n- node (is node)\n- version (version of Risuai)\n- major (Major version of risuai)\n- lang (current language code)\n- browserlang (same as navigator.language in js)\n- modelshortname (returns current model's short name)\n- modelname (returns current model's name)\n- modelformat (returns current model's format)\n- modelprovider (returns current model's provider)\n- modeltokenizer (returns current model's tokenizer)\n- risutype (returns current risuai type like node web and etc.)\n- maxcontext (returns current max context)" },
      { macro: "{{iserror::string}}", description: "Check if string is error" },
      { macro: "{{asset::name}}", description: "Returns a asset image named first argument" },
      { macro: "{{emotion::name}}", description: "Returns a emotion image named first argument" },
      { macro: "{{audio::name}}", description: "Returns a audio named first argument" },
      { macro: "{{bg::name}}", description: "Returns a image with width and height as 100% named first argument. mostly used with background embedding feature in character" },
      { macro: "{{video::name}}", description: "Returns a video named first argument" },
      { macro: "{{video-img::name}}", description: "Return a video that is styled like a image named first argument" },
      { macro: "{{path::name}}", description: "Returns a string which is a path to the file named first argument", aliases: ["raw"] },
      { macro: "{{image::name}}", description: "Returns a image named first argument" },
      { macro: "{{img::name}}", description: "Returns a image named first argument but without styling" },
      { macro: "{{bgm::name}}", description: "Returns a audio which is hidden named first argument" },
      { macro: "{{inlay::name}}", description: "Returns a image from inlay data named first argument" },
      { macro: "{{inlayed::name}}", description: "Returns a image from inlay data named first argument but with styling" },
      { macro: "{{inlayeddata::name}}", description: "Returns a image from inlay data named first argument but with styling and data. unlike inlayed it is also sent to the AI when character sent with this function" },
      { macro: "{{?}}", description: "Do math operations doesn't follow the usual syntax of arguments supports + - * / ^ % < > <= >= || && == != !" },
      { macro: "{{random::arg1::arg2::arg3::...}}", description: "Returns a random selection of arguments" },
      { macro: "{{pick::arg1::arg2::arg3::...}}", description: "same as random but seed is fixed by message index resulting consistent output" },
      { macro: "{{roll::number}}", description: "Returns a random integer from 1 to first argument" },
      { macro: "{{rollp::number}}", description: "same as roll but seed is fixed by message index resulting consistent output" },
      { macro: "{{slot::name}}", description: "returns the current element being iterated over, identified by named first argument" },
    ],
  },
];
