/**
 * The component catalog's imperative shell: walks the UI tree, runs catalog-lib's pure extraction
 * over every file, and turns the result into docs/reference/components.md. Covers BOTH renderer
 * idioms live during the ADR-008 conversion: React components under src/ui/components, src/ui/apps,
 * src/ui/shell (.tsx), and today's vanilla create/build/swatch/inject factories in src/ui/_shared
 * (.ts). A drop-in folder gains no special treatment here - the glob patterns are the one seam,
 * matching the repo's folders-as-schema doctrine.
 *
 * Modes:
 *   (default)  write docs/reference/components.md
 *   --check    exit 2 if the on-disk file would differ from a fresh generation (pre-commit gate)
 *   --digest   print a compact one-line-per-entry listing to stdout (SessionStart context injection)
 *
 * Run: bun run scripts/hooks/component-catalog.ts [--check|--digest]
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { extractCatalogEntries, type CatalogEntry } from "./catalog-lib";

const GLOBS = [
  "src/ui/components/**/*.tsx",
  "src/ui/apps/**/*.tsx",
  "src/ui/shell/**/*.tsx",
  "src/ui/_shared/*.ts",
];

const OUT_PATH = "docs/reference/components.md";

/** Every file the catalog scans, deduped and sorted for a deterministic scan order. */
function collectFiles(): string[] {
  const files = new Set<string>();
  for (const pattern of GLOBS) {
    for (const f of new Bun.Glob(pattern).scanSync({ cwd: process.cwd() })) {
      const p = f.replace(/\\/g, "/");
      if (/\.test\.tsx?$/.test(p)) continue;
      files.add(p);
    }
  }
  return [...files].sort();
}

function allEntries(files: string[]): CatalogEntry[] {
  const entries: CatalogEntry[] = [];
  for (const file of files) {
    entries.push(...extractCatalogEntries(file, readFileSync(file, "utf8")));
  }
  // kind then name (both alphabetical): "component" sorts before "legacy-widget" on its own, so this
  // one comparator gives the grouped, deterministic order the table renders in.
  return entries.sort((a, b) => (a.kind === b.kind ? a.name.localeCompare(b.name) : a.kind.localeCompare(b.kind)));
}

const escapeCell = (s: string): string => s.replace(/\|/g, "\\|");

function table(rows: CatalogEntry[], emptyNote: string): string {
  if (rows.length === 0) return `_${emptyNote}_\n`;
  const body = rows
    .map((e) => `| ${escapeCell(e.name)} | ${escapeCell(e.file)} | ${escapeCell(e.signature)} | ${escapeCell(e.doc)} |`)
    .join("\n");
  return `| Name | File | Signature | Doc |\n| --- | --- | --- | --- |\n${body}\n`;
}

function renderMarkdown(entries: CatalogEntry[]): string {
  const components = entries.filter((e) => e.kind === "component");
  const legacy = entries.filter((e) => e.kind === "legacy-widget");
  return `# Component catalog

Auto-generated by \`scripts/hooks/component-catalog.ts\` from exported UI entries under
\`src/ui/components\`, \`src/ui/apps\`, \`src/ui/shell\` (\`.tsx\` React components, ADR-008) and
\`src/ui/_shared\` (\`.ts\` legacy widget factories - the vanilla surfaces the conversion is
replacing). Do not hand-edit: regenerate with \`bun run scripts/hooks/component-catalog.ts\`. A
pre-commit gate (\`--check\`) fails the commit when this file drifts from the real exports.

## Components (React, \`.tsx\`)

${table(components, "None yet - the .tsx conversion (ADR-008) has not landed a component here")}
## Legacy widgets (\`src/ui/_shared\`, vanilla)

${table(legacy, "None found")}`;
}

function main(): number {
  const entries = allEntries(collectFiles());

  if (process.argv.includes("--digest")) {
    for (const e of entries) console.log(`${e.kind}\t${e.name}\t${e.file}\t${e.signature}`);
    return 0;
  }

  const content = renderMarkdown(entries);

  if (process.argv.includes("--check")) {
    const onDisk = existsSync(OUT_PATH) ? readFileSync(OUT_PATH, "utf8") : "";
    if (onDisk !== content) {
      console.error(`component-catalog: ${OUT_PATH} is stale. Run: bun run scripts/hooks/component-catalog.ts`);
      return 2;
    }
    return 0;
  }

  writeFileSync(OUT_PATH, content);
  return 0;
}

process.exit(main());
